#!/usr/bin/env node
// Rebuild Pip's local narration. Requires ~/bin/tts.py and its configured Azure access.
// No credentials are written into the site. Existing clips are cached; remove a
// specific MP3 to regenerate it. The content-addressed log detects text changes.
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { spawn } = require('node:child_process');
const { createHash } = require('node:crypto');
const root = path.resolve(__dirname, '..');
const app = fs.readFileSync(path.join(root,'app.js'),'utf8');
const extended = fs.readFileSync(path.join(root,'assets/country-data.js'),'utf8');
const countries = vm.runInNewContext(extended+'\n'+app.slice(app.indexOf('const COUNTRIES ='),app.indexOf('const BY ='))+'COUNTRIES;');
const out = path.join(root,'assets/audio');fs.mkdirSync(out,{recursive:true});
const jobs=[], manifest={};
function clip(id,text){jobs.push({id,text});return `assets/audio/${id}.mp3`;}
function cue(text,id){manifest[text]=[clip(id,text)];}
const welcome='Hello, little explorer! I’m Pip. Let’s meet a new country.';
cue(welcome,'welcome');
cue('Pick a country to begin.','pick-country');
const found=clip('found','You found it! What a wonderful little explorer.');
clip('retry','A good try! Let’s have another little look.');
const stamp=clip('stamp','Hello, world! You found a country’s flag, and its home. A happy little memory for your passport!');
cue('Five little discoveries! You looked, you tried, and you learned. What a wonderful explorer.','finish');
cue('France and Italy are flag twins! Both have three tall stripes. France starts with blue. Italy starts with green. The middle is white and the right is red.','twins');
const regions={};
for(const r of [...new Set(countries.map(f=>f.r))])regions[r]=clip('region-'+r.toLowerCase().replaceAll(' ','-'),`${r}! Look for ${r} on the map. Take your time.`);
for(const [index,f] of countries.entries()){
 const learn=`Hello, ${f.n}! ${f.hint} ${f.geo}`;
 cue(learn,`learn-${f.c}`);
 const question=`Can you find the flag of ${f.n}? ${f.hint}`;
 const home=`${f.n} is in ${f.r}. Look for ${f.r} on the map.`;
 // Reuse the short country story as a flag clue for the extended world.
 // Six shared region clips keep every location clue local without hundreds
 // of nearly identical files. Already-recorded starter clips are retained.
 if(index<24){cue(question,`flag-${f.c}`);cue(home,`home-${f.c}`);}
 else{manifest[question]=manifest[learn];manifest[home]=[regions[f.r]];}
 const hello=index<24?clip(`hello-${f.c}`,`You found it! Hello, ${f.n}!`):found;
 manifest[`You found it! Hello, ${f.n}!`]=[hello];
 manifest[`You found its home! ${f.n} is in ${f.r}.`]=[found];
 manifest[`Hello, world! You found the flag and home of ${f.n}. Your passport has a new memory.`]=[stamp];
}
for(const [id,text] of Object.entries({circle:'Find a red circle!',stars:'Find a starry flag!',cross:'Find a cross!',vertical:'Find stripes standing up!',horizontal:'Find stripes lying down!'}))cue(text,`shape-${id}`);
fs.writeFileSync(path.join(root,'assets/audio-manifest.js'),'/* Local Olivia / MAI-Voice-2 narration. Generated by scripts/generate-audio.cjs. */\nconst PIP_AUDIO = '+JSON.stringify(manifest,null,2)+';\n');
if(process.argv.includes('--manifest-only'))process.exit(0);
const cacheFile=path.join(out,'generation.json');let cache={};try{cache=JSON.parse(fs.readFileSync(cacheFile,'utf8'));}catch{}
let completed=0;
async function make(job){
 const output=path.join(out,job.id+'.mp3');
 const hash=createHash('sha256').update(job.text+'|en-US-Olivia:MAI-Voice-2|-8%|mp3-hq').digest('hex');
 if(fs.existsSync(output)&&cache[job.id]===hash){completed++;return;}
 // The initial sample uses this exact text and generation settings.
 if(job.id==='learn-jp'&&fs.existsSync(output)&&!cache[job.id]){cache[job.id]=hash;completed++;return;}
 for(let attempt=1;attempt<=3;attempt++){
  try{
   await new Promise((resolve,reject)=>{
    const child=spawn(path.join(process.env.HOME,'bin/tts.py'),[job.text,'--voice','en-US-Olivia:MAI-Voice-2','--rate=-8%','--format','mp3-hq','-o',output],{stdio:['ignore','ignore','pipe'],timeout:90000});
    let error='';child.stderr.on('data',x=>error+=x);
    child.on('error',reject);child.on('exit',code=>code===0?resolve():reject(new Error(`${job.id}: exit ${code}: ${error}`)));
   });
   break;
  }catch(error){
   if(attempt===3)throw error;
   console.log(`Retrying ${job.id} after transient synthesis failure (${attempt}/3)`);
   await new Promise(resolve=>setTimeout(resolve,attempt*1500));
  }
 }
 cache[job.id]=hash;completed++;
 fs.writeFileSync(cacheFile,JSON.stringify(cache,null,2)+'\n');
 console.log(`${completed}/${jobs.length} recorded: ${job.id}`);
}
(async()=>{
 let i=0;
 const results=await Promise.allSettled(Array.from({length:6},async()=>{while(i<jobs.length)await make(jobs[i++]);}));
 const failed=results.find(r=>r.status==='rejected');
 if(failed)throw failed.reason;
 fs.writeFileSync(cacheFile,JSON.stringify(cache,null,2)+'\n');
 fs.writeFileSync(path.join(root,'assets/audio-manifest.js'),'/* Local Olivia / MAI-Voice-2 narration. Generated by scripts/generate-audio.cjs. */\nconst PIP_AUDIO = '+JSON.stringify(manifest,null,2)+';\n');
 console.log(`Ready: ${jobs.length} audio clips, ${Object.keys(manifest).length} narrated cues.`);
})().catch(e=>{console.error(e.message);process.exitCode=1;});
