import { COUNTRIES, country } from "../../platform/catalog";
import { countryCard } from "../../shared/ui/components";
import { worldMap } from "../../shared/ui/map";
import { flag, icon, mascot } from "../../shared/ui/art";

function discoveryCards() {
  return `<div class="discovery-grid">
<button class="discovery-card yellow" data-action="shapes"><span class="card-kicker"><i class="mini-dot"></i>LOOK & LEARN</span><span class="card-art"><span class="shape-dot"></span><img class="art-flag" src="${flag("jp")}" alt="Japan"><img class="art-flag second" src="${flag("br")}" alt="Brazil"><span class="shape-star">✦</span></span><h3>Spot a shape</h3><p class="card-desc">A circle, a star… a whole new country!</p><span class="card-bottom">BIG SHAPES. LITTLE DISCOVERIES.<span class="circle-arrow">${icon("arrow")}</span></span></button>
<button class="discovery-card lavender" data-action="stripes"><span class="card-kicker"><i class="mini-dot"></i>PATTERN PLAY</span><span class="card-art"><img class="art-flag" src="${flag("fr")}" alt="France"><img class="art-flag second" src="${flag("in")}" alt="India"><img class="art-flag third" src="${flag("ng")}" alt="Nigeria"></span><h3>Follow the stripes</h3><p class="card-desc">Standing up or lying down?</p><span class="card-bottom">COLORS WITH A CLEVER LITTLE CLUE.<span class="circle-arrow">${icon("arrow")}</span></span></button>
<button class="discovery-card green" data-action="twins"><span class="card-kicker"><i class="mini-dot"></i>LITTLE DETECTIVES</span><span class="card-art"><img class="art-flag" src="${flag("fr")}" alt="France"><span class="art-equal">≠</span><img class="art-flag second" src="${flag("it")}" alt="Italy"></span><h3>Find flag twins</h3><p class="card-desc">Almost the same. Can you spot it?</p><span class="card-bottom">ONE TINY DIFFERENCE. BIG AHA!<span class="circle-arrow">${icon("arrow")}</span></span></button>
</div>`;
}
export function home(stamps: readonly string[]): string {
  return `<div class="page-enter"><section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><div class="eyebrow"><i></i>FOR LITTLE EXPLORERS & BIG IMAGINATIONS</div><h1 id="hero-title"><span class="line">Small flags.</span><span class="line orange">BIG adventures.</span></h1><p class="hero-desc">Every flag has a story. Every country, a home.<br><strong>Let’s discover them, one happy little hop at a time.</strong></p><button class="button primary" data-action="start">Let’s go exploring ${icon("arrow")}</button><a href="#world" class="choose-path">Or choose your own learning path →</a><p class="hero-footnote">${icon("heart")} Made for ages 3–6 <span class="dot">·</span> Grown-ups welcome, too</p></div>
<div class="world-stage"><div class="stage-top"><span>YOUR WHOLE WORLD OF WONDER</span><div class="compass-art" aria-hidden="true">✧</div></div><span class="little-star" aria-hidden="true">✦</span><div class="postmark" aria-hidden="true">LITTLE ATLAS<b>✈</b>LET’S GO!</div><div class="hero-map">${worldMap({ pins: ["ca", "br", "fr", "ke", "jp", "au"].map(country), interactive: true })}</div><div class="mascot-speech">Hi, I’m Pip! Let’s explore.</div><div class="mascot">${mascot()}</div><div class="map-lesson"><span class="hand" aria-hidden="true">☝</span><span><b>A flag is a little hello.</b><br>Tap one. Meet somewhere new!</span></div><span class="world-caption">One planet. So many new friends.</span></div></section>
<div class="promise"><span>${icon("sound")} Listen, look & learn</span><span>${icon("globe")} Real places. Playful discoveries.</span><span>${icon("heart")} No timers. Just tiny triumphs.</span></div>
<section aria-labelledby="discover-title"><div class="section-heading"><div><h2 id="discover-title">There’s a little clue in every flag.</h2><p>Start with what you see. Remember where it takes you.</p></div><span class="aside-note">${icon("spark")} A few minutes. A new discovery.</span></div>${discoveryCards()}</section>
<section aria-labelledby="next-stop"><div class="section-heading journey-heading"><div><h2 id="next-stop">Where shall we hop next?</h2><p>Six little hellos from around the world.</p></div><a class="text-button" href="#world">Explore all ${COUNTRIES.length} entries ${icon("arrow")}</a></div><div class="country-row">${["jp", "br", "ca", "fr", "ke", "au"].map((code) => countryCard(country(code), stamps)).join("")}</div></section>
<div class="passport-callout">${icon("passport")}<div><h3>Little adventures. A passport full of memories.</h3><p>Meet a country, find its flag and its home. Collect a happy little stamp.</p></div><a class="text-button" href="#passport">My passport ${icon("arrow")}</a></div></div>`;
}
